"""add profile table

Revision ID: 13811af301c7
Revises: d5fab12965b9
Create Date: 2026-03-21 16:54:14.007803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13811af301c7'
down_revision: Union[str, Sequence[str], None] = 'd5fab12965b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.BigInteger(), nullable=False),
    sa.Column('height', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='user_gender_enum'), nullable=False),
    sa.Column('activity_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='user_activity_level_enum'), nullable=False),
    sa.Column('goal', sa.Enum('LOOSE_WEIGHT', 'BUILD_MUSCLE', 'STAY_FIT', 'IMPROVE_FLEXIBILITY', name='user_goal_enum'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("ALTER TYPE user_status_enum ADD VALUE IF NOT EXISTS 'NEED_ONBORDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
