"""add benefits table, upgrade exercises

Revision ID: 214f91bc96c6
Revises: 57c7a50cb8b0
Create Date: 2026-02-21 19:19:07.297913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214f91bc96c6'
down_revision: Union[str, Sequence[str], None] = '57c7a50cb8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_benefits',
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content')
    )
    op.add_column('exercises', sa.Column('duration', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('calories', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('sets', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('reps', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('image_url', sa.String(length=512), nullable=False))
    op.drop_column('exercises', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('exercises', 'image_url')
    op.drop_column('exercises', 'reps')
    op.drop_column('exercises', 'sets')
    op.drop_column('exercises', 'calories')
    op.drop_column('exercises', 'duration')
    op.drop_table('exercise_benefits')
    # ### end Alembic commands ###
