"""add otp table

Revision ID: 57c7a50cb8b0
Revises: d032a1752221
Create Date: 2026-02-14 16:18:57.438605

"""
from app.enums.user_status import UserStatusEnum
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '57c7a50cb8b0'
down_revision: Union[str, Sequence[str], None] = 'd032a1752221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTER', name='otp_purpose_enum'), nullable=False),
    sa.Column('code_hash', sa.LargeBinary(), nullable=False),
    sa.Column('resend_available_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    user_status_enum = postgresql.ENUM(UserStatusEnum, name="user_status_enum")
    user_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('status', user_status_enum, nullable=False, server_default=sa.text("'ACTIVE'")))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text("'true'")))
    op.drop_column('users', 'status')

    user_status_enum = postgresql.ENUM(UserStatusEnum, name="user_status_enum")
    user_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_table('otp_codes')
    # ### end Alembic commands ###
