"""add fat to nutrition

Revision ID: 67f4b52298c0
Revises: 8e8ceb2ce70e
Create Date: 2026-03-17 19:18:37.391511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f4b52298c0'
down_revision: Union[str, Sequence[str], None] = '8e8ceb2ce70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritions', sa.Column('fat', sa.Float(), nullable=True))
    op.execute("UPDATE nutritions SET fat = 0")
    op.alter_column('nutritions', 'fat', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutritions', 'fat')
    # ### end Alembic commands ###
