"""add nutrition table

Revision ID: 8e8ceb2ce70e
Revises: 5d5a926f8e35
Create Date: 2026-03-15 21:56:03.568054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8ceb2ce70e'
down_revision: Union[str, Sequence[str], None] = '5d5a926f8e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutritions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('meal_name', sa.String(length=200), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('serving_amount', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutritions')
    # ### end Alembic commands ###
