"""drop unique const on benefits.content

Revision ID: b6c699825400
Revises: 214f91bc96c6
Create Date: 2026-02-22 13:39:17.085792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c699825400'
down_revision: Union[str, Sequence[str], None] = '214f91bc96c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercise_benefits_content_key'), 'exercise_benefits', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('exercise_benefits_content_key'), 'exercise_benefits', ['content'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
