"""add image url to food

Revision ID: d5fab12965b9
Revises: 67f4b52298c0
Create Date: 2026-03-18 16:29:21.434038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fab12965b9'
down_revision: Union[str, Sequence[str], None] = '67f4b52298c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritions', sa.Column('food_image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutritions', 'food_image_url')
    # ### end Alembic commands ###
